/**
 * MRT Station Data
 * Station names and route information sourced from public information provided by:
 * - Taipei Rapid Transit Corporation (TRTC) — www.metro.taipei
 * - Taoyuan Metro Corporation (TYMC) — www.tymetro.com.tw
 * Used for informational and navigation assistance purposes only.
 * All station names and route designations are trademarks of their respective operators.
 */

window.MRT_STATIONS = [
  // 淡水信義線 Tamsui-Xinyi Line (紅線 Red)
  {id:'tamsui',zh:'淡水',en:'Tamsui',line:'淡水信義線',lineEn:'Tamsui-Xinyi Line',lineColor:'#e53935'},
  {id:'hongshulin',zh:'紅樹林',en:'Hongshulin',line:'淡水信義線',lineEn:'Tamsui-Xinyi Line',lineColor:'#e53935'},
  {id:'zhuwei',zh:'竹圍',en:'Zhuwei',line:'淡水信義線',lineEn:'Tamsui-Xinyi Line',lineColor:'#e53935'},
  {id:'guandu',zh:'關渡',en:'Guandu',line:'淡水信義線',lineEn:'Tamsui-Xinyi Line',lineColor:'#e53935'},
  {id:'fuxinggang',zh:'復興崗',en:'Fuxinggang',line:'淡水信義線',lineEn:'Tamsui-Xinyi Line',lineColor:'#e53935'},
  {id:'zhongyi',zh:'忠義',en:'Zhongyi',line:'淡水信義線',lineEn:'Tamsui-Xinyi Line',lineColor:'#e53935'},
  {id:'beitou',zh:'北投',en:'Beitou',line:'淡水信義線',lineEn:'Tamsui-Xinyi Line',lineColor:'#e53935'},
  {id:'xinbeitou',zh:'新北投',en:'Xinbeitou',line:'淡水信義線',lineEn:'Tamsui-Xinyi Line',lineColor:'#e53935'},
  {id:'qiyan',zh:'奇岩',en:'Qiyan',line:'淡水信義線',lineEn:'Tamsui-Xinyi Line',lineColor:'#e53935'},
  {id:'mingde',zh:'明德',en:'Mingde',line:'淡水信義線',lineEn:'Tamsui-Xinyi Line',lineColor:'#e53935'},
  {id:'shipai',zh:'石牌',en:'Shipai',line:'淡水信義線',lineEn:'Tamsui-Xinyi Line',lineColor:'#e53935'},
  {id:'zhishan',zh:'芝山',en:'Zhishan',line:'淡水信義線',lineEn:'Tamsui-Xinyi Line',lineColor:'#e53935'},
  {id:'tianmu',zh:'天母',en:'Tianmu',line:'淡水信義線',lineEn:'Tamsui-Xinyi Line',lineColor:'#e53935'},
  {id:'jiantan',zh:'劍潭',en:'Jiantan',line:'淡水信義線',lineEn:'Tamsui-Xinyi Line',lineColor:'#e53935'},
  {id:'shilin',zh:'士林',en:'Shilin',line:'淡水信義線',lineEn:'Tamsui-Xinyi Line',lineColor:'#e53935'},
  {id:'yuanshan',zh:'圓山',en:'Yuanshan',line:'淡水信義線',lineEn:'Tamsui-Xinyi Line',lineColor:'#e53935'},
  {id:'minquan_w',zh:'民權西路',en:'Minquan W. Rd.',line:'淡水信義線',lineEn:'Tamsui-Xinyi Line',lineColor:'#e53935'},
  {id:'shuanglian',zh:'雙連',en:'Shuanglian',line:'淡水信義線',lineEn:'Tamsui-Xinyi Line',lineColor:'#e53935'},
  {id:'zhongshan',zh:'中山',en:'Zhongshan',line:'淡水信義線',lineEn:'Tamsui-Xinyi Line',lineColor:'#e53935'},
  {id:'taida_hosp',zh:'台大醫院',en:'NTU Hospital',line:'淡水信義線',lineEn:'Tamsui-Xinyi Line',lineColor:'#e53935'},
  {id:'taipei_main',zh:'台北車站',en:'Taipei Main Station',line:'淡水信義線',lineEn:'Tamsui-Xinyi Line',lineColor:'#e53935'},
  {id:'cksmh',zh:'中正紀念堂',en:'Chiang Kai-Shek Memorial Hall',line:'淡水信義線',lineEn:'Tamsui-Xinyi Line',lineColor:'#e53935'},
  {id:'dongmen',zh:'東門',en:'Dongmen',line:'淡水信義線',lineEn:'Tamsui-Xinyi Line',lineColor:'#e53935'},
  {id:'daan',zh:'大安',en:"Da'an",line:'淡水信義線',lineEn:'Tamsui-Xinyi Line',lineColor:'#e53935'},
  {id:'daan_park',zh:'大安森林公園',en:"Da'an Forest Park",line:'淡水信義線',lineEn:'Tamsui-Xinyi Line',lineColor:'#e53935'},
  {id:'xinyi_anhe',zh:'信義安和',en:'Xinyi Anhe',line:'淡水信義線',lineEn:'Tamsui-Xinyi Line',lineColor:'#e53935'},
  {id:'taipei101',zh:'台北101/世貿',en:'Taipei 101/World Trade Center',line:'淡水信義線',lineEn:'Tamsui-Xinyi Line',lineColor:'#e53935'},
  {id:'xiangshan',zh:'象山',en:'Xiangshan',line:'淡水信義線',lineEn:'Tamsui-Xinyi Line',lineColor:'#e53935'},

  // 松山新店線 Songshan-Xindian Line (綠線 Green)
  {id:'songshan',zh:'松山',en:'Songshan',line:'松山新店線',lineEn:'Songshan-Xindian Line',lineColor:'#43a047'},
  {id:'nanjing_fuxing',zh:'南京復興',en:'Nanjing Fuxing',line:'松山新店線',lineEn:'Songshan-Xindian Line',lineColor:'#43a047'},
  {id:'zhongxiao_fuxing',zh:'忠孝復興',en:'Zhongxiao Fuxing',line:'松山新店線',lineEn:'Songshan-Xindian Line',lineColor:'#43a047'},
  {id:'zhongxiao_xinsheng',zh:'忠孝新生',en:'Zhongxiao Xinsheng',line:'松山新店線',lineEn:'Songshan-Xindian Line',lineColor:'#43a047'},
  {id:'guting',zh:'古亭',en:'Guting',line:'松山新店線',lineEn:'Songshan-Xindian Line',lineColor:'#43a047'},
  {id:'taipower',zh:'台電大樓',en:'Taipower Building',line:'松山新店線',lineEn:'Songshan-Xindian Line',lineColor:'#43a047'},
  {id:'gongguan',zh:'公館',en:'Gongguan',line:'松山新店線',lineEn:'Songshan-Xindian Line',lineColor:'#43a047'},
  {id:'wanlong',zh:'萬隆',en:'Wanlong',line:'松山新店線',lineEn:'Songshan-Xindian Line',lineColor:'#43a047'},
  {id:'jingmei',zh:'景美',en:'Jingmei',line:'松山新店線',lineEn:'Songshan-Xindian Line',lineColor:'#43a047'},
  {id:'dapinglin',zh:'大坪林',en:'Dapinglin',line:'松山新店線',lineEn:'Songshan-Xindian Line',lineColor:'#43a047'},
  {id:'qizhang',zh:'七張',en:'Qizhang',line:'松山新店線',lineEn:'Songshan-Xindian Line',lineColor:'#43a047'},
  {id:'xindian_city_hall',zh:'新店市政府',en:'Xindian City Hall',line:'松山新店線',lineEn:'Songshan-Xindian Line',lineColor:'#43a047'},
  {id:'xindian',zh:'新店',en:'Xindian',line:'松山新店線',lineEn:'Songshan-Xindian Line',lineColor:'#43a047'},
  {id:'xiaobitan',zh:'小碧潭',en:'Xiaobitan',line:'松山新店線',lineEn:'Songshan-Xindian Line',lineColor:'#43a047'},
  {id:'beimen',zh:'北門',en:'Beimen',line:'松山新店線',lineEn:'Songshan-Xindian Line',lineColor:'#43a047'},
  {id:'ximen',zh:'西門',en:'Ximen',line:'松山新店線',lineEn:'Songshan-Xindian Line',lineColor:'#43a047'},
  {id:'xiaonanmen',zh:'小南門',en:'Xiaonanmen',line:'松山新店線',lineEn:'Songshan-Xindian Line',lineColor:'#43a047'},

  // 中和新蘆線 Zhonghe-Xinlu Line (橘線 Orange)
  {id:'nanshijiao',zh:'南勢角',en:'Nanshijiao',line:'中和新蘆線',lineEn:'Zhonghe-Xinlu Line',lineColor:'#fb8c00'},
  {id:'jingping',zh:'景平',en:'Jingping',line:'中和新蘆線',lineEn:'Zhonghe-Xinlu Line',lineColor:'#fb8c00'},
  {id:'jingan',zh:'景安',en:"Jing'an",line:'中和新蘆線',lineEn:'Zhonghe-Xinlu Line',lineColor:'#fb8c00'},
  {id:'yongan_market',zh:'永安市場',en:"Yong'an Market",line:'中和新蘆線',lineEn:'Zhonghe-Xinlu Line',lineColor:'#fb8c00'},
  {id:'dingxi',zh:'頂溪',en:'Dingxi',line:'中和新蘆線',lineEn:'Zhonghe-Xinlu Line',lineColor:'#fb8c00'},
  {id:'guting_o',zh:'古亭',en:'Guting',line:'中和新蘆線',lineEn:'Zhonghe-Xinlu Line',lineColor:'#fb8c00'},
  {id:'dongmen_o',zh:'東門',en:'Dongmen',line:'中和新蘆線',lineEn:'Zhonghe-Xinlu Line',lineColor:'#fb8c00'},
  {id:'zhongxiao_xinsheng_o',zh:'忠孝新生',en:'Zhongxiao Xinsheng',line:'中和新蘆線',lineEn:'Zhonghe-Xinlu Line',lineColor:'#fb8c00'},
  {id:'songjiang_nanjing',zh:'松江南京',en:'Songjiang Nanjing',line:'中和新蘆線',lineEn:'Zhonghe-Xinlu Line',lineColor:'#fb8c00'},
  {id:'xingtian',zh:'行天宮',en:'Xingtian Temple',line:'中和新蘆線',lineEn:'Zhonghe-Xinlu Line',lineColor:'#fb8c00'},
  {id:'zhongshan_o',zh:'中山',en:'Zhongshan',line:'中和新蘆線',lineEn:'Zhonghe-Xinlu Line',lineColor:'#fb8c00'},
  {id:'minquan_w_o',zh:'民權西路',en:'Minquan W. Rd.',line:'中和新蘆線',lineEn:'Zhonghe-Xinlu Line',lineColor:'#fb8c00'},
  {id:'daqiaotou',zh:'大橋頭',en:'Daqiaotou',line:'中和新蘆線',lineEn:'Zhonghe-Xinlu Line',lineColor:'#fb8c00'},
  {id:'dalong',zh:'大龍',en:'Dalong',line:'中和新蘆線',lineEn:'Zhonghe-Xinlu Line',lineColor:'#fb8c00'},
  {id:'yuanshan_o',zh:'圓山',en:'Yuanshan',line:'中和新蘆線',lineEn:'Zhonghe-Xinlu Line',lineColor:'#fb8c00'},
  {id:'jiannan_rd',zh:'劍南路',en:'Jiannan Rd.',line:'中和新蘆線',lineEn:'Zhonghe-Xinlu Line',lineColor:'#fb8c00'},
  {id:'xinzhuang',zh:'新莊',en:'Xinzhuang',line:'中和新蘆線',lineEn:'Zhonghe-Xinlu Line',lineColor:'#fb8c00'},
  {id:'taishan_guihe',zh:'泰山貴和',en:'Taishan Guihe',line:'中和新蘆線',lineEn:'Zhonghe-Xinlu Line',lineColor:'#fb8c00'},
  {id:'furen',zh:'輔大',en:'Fu Jen University',line:'中和新蘆線',lineEn:'Zhonghe-Xinlu Line',lineColor:'#fb8c00'},
  {id:'danfeng',zh:'丹鳳',en:'Danfeng',line:'中和新蘆線',lineEn:'Zhonghe-Xinlu Line',lineColor:'#fb8c00'},
  {id:'luzhou',zh:'蘆洲',en:'Luzhou',line:'中和新蘆線',lineEn:'Zhonghe-Xinlu Line',lineColor:'#fb8c00'},

  // 板南線 Bannan Line (藍線 Blue)
  {id:'dingpu',zh:'頂埔',en:'Dingpu',line:'板南線',lineEn:'Bannan Line',lineColor:'#1e88e5'},
  {id:'tucheng',zh:'土城',en:'Tucheng',line:'板南線',lineEn:'Bannan Line',lineColor:'#1e88e5'},
  {id:'haishan',zh:'海山',en:'Haishan',line:'板南線',lineEn:'Bannan Line',lineColor:'#1e88e5'},
  {id:'yongning',zh:'永寧',en:'Yongning',line:'板南線',lineEn:'Bannan Line',lineColor:'#1e88e5'},
  {id:'fuzhong',zh:'府中',en:'Fuzhong',line:'板南線',lineEn:'Bannan Line',lineColor:'#1e88e5'},
  {id:'banqiao',zh:'板橋',en:'Banqiao',line:'板南線',lineEn:'Bannan Line',lineColor:'#1e88e5'},
  {id:'xinpu',zh:'新埔',en:'Xinpu',line:'板南線',lineEn:'Bannan Line',lineColor:'#1e88e5'},
  {id:'jiangzicui',zh:'江子翠',en:'Jiangzicui',line:'板南線',lineEn:'Bannan Line',lineColor:'#1e88e5'},
  {id:'longshan_temple',zh:'龍山寺',en:'Longshan Temple',line:'板南線',lineEn:'Bannan Line',lineColor:'#1e88e5'},
  {id:'ximen_b',zh:'西門',en:'Ximen',line:'板南線',lineEn:'Bannan Line',lineColor:'#1e88e5'},
  {id:'beimen_b',zh:'北門',en:'Beimen',line:'板南線',lineEn:'Bannan Line',lineColor:'#1e88e5'},
  {id:'taipei_main_b',zh:'台北車站',en:'Taipei Main Station',line:'板南線',lineEn:'Bannan Line',lineColor:'#1e88e5'},
  {id:'shandao_temple',zh:'善導寺',en:'Shandao Temple',line:'板南線',lineEn:'Bannan Line',lineColor:'#1e88e5'},
  {id:'zhongxiao_xinsheng_b',zh:'忠孝新生',en:'Zhongxiao Xinsheng',line:'板南線',lineEn:'Bannan Line',lineColor:'#1e88e5'},
  {id:'zhongxiao_fuxing_b',zh:'忠孝復興',en:'Zhongxiao Fuxing',line:'板南線',lineEn:'Bannan Line',lineColor:'#1e88e5'},
  {id:'zhongxiao_dunhua',zh:'忠孝敦化',en:'Zhongxiao Dunhua',line:'板南線',lineEn:'Bannan Line',lineColor:'#1e88e5'},
  {id:'guofu',zh:'國父紀念館',en:'Sun Yat-Sen Memorial Hall',line:'板南線',lineEn:'Bannan Line',lineColor:'#1e88e5'},
  {id:'market',zh:'市政府',en:'City Hall',line:'板南線',lineEn:'Bannan Line',lineColor:'#1e88e5'},
  {id:'yongchun',zh:'永春',en:'Yongchun',line:'板南線',lineEn:'Bannan Line',lineColor:'#1e88e5'},
  {id:'houshanpi',zh:'後山埤',en:'Houshanpi',line:'板南線',lineEn:'Bannan Line',lineColor:'#1e88e5'},
  {id:'kunyang',zh:'昆陽',en:'Kunyang',line:'板南線',lineEn:'Bannan Line',lineColor:'#1e88e5'},
  {id:'nangang',zh:'南港',en:'Nangang',line:'板南線',lineEn:'Bannan Line',lineColor:'#1e88e5'},
  {id:'nangang_exhibition',zh:'南港展覽館',en:'Nangang Exhibition Center',line:'板南線',lineEn:'Bannan Line',lineColor:'#1e88e5'},

  // 文湖線 Wenhu Line (棕線 Brown)
  {id:'neihu',zh:'內湖',en:'Neihu',line:'文湖線',lineEn:'Wenhu Line',lineColor:'#795548'},
  {id:'donghu',zh:'東湖',en:'Donghu',line:'文湖線',lineEn:'Wenhu Line',lineColor:'#795548'},
  {id:'huanshan',zh:'環山',en:'Huanshan',line:'文湖線',lineEn:'Wenhu Line',lineColor:'#795548'},
  {id:'xihuzui',zh:'西湖',en:'Xihu',line:'文湖線',lineEn:'Wenhu Line',lineColor:'#795548'},
  {id:'jiannan',zh:'劍南路',en:'Jiannan Rd.',line:'文湖線',lineEn:'Wenhu Line',lineColor:'#795548'},
  {id:'dahu_park',zh:'大湖公園',en:'Dahu Park',line:'文湖線',lineEn:'Wenhu Line',lineColor:'#795548'},
  {id:'gangqian',zh:'港墘',en:'Gangqian',line:'文湖線',lineEn:'Wenhu Line',lineColor:'#795548'},
  {id:'wenhu',zh:'文湖',en:'Wenhu',line:'文湖線',lineEn:'Wenhu Line',lineColor:'#795548'},
  {id:'wende',zh:'文德',en:'Wende',line:'文湖線',lineEn:'Wenhu Line',lineColor:'#795548'},
  {id:'nankang_jr',zh:'南京三民',en:'Nanjing Sanmin',line:'文湖線',lineEn:'Wenhu Line',lineColor:'#795548'},
  {id:'songshan_wh',zh:'松山機場',en:'Songshan Airport',line:'文湖線',lineEn:'Wenhu Line',lineColor:'#795548'},
  {id:'zhongshan_jr',zh:'中山國中',en:'Zhongshan Junior High School',line:'文湖線',lineEn:'Wenhu Line',lineColor:'#795548'},
  {id:'daan_wh',zh:'大安',en:"Da'an",line:'文湖線',lineEn:'Wenhu Line',lineColor:'#795548'},
  {id:'technology_bldg',zh:'科技大樓',en:'Technology Building',line:'文湖線',lineEn:'Wenhu Line',lineColor:'#795548'},
  {id:'liuzhangli',zh:'六張犁',en:'Liuzhangli',line:'文湖線',lineEn:'Wenhu Line',lineColor:'#795548'},
  {id:'linguang',zh:'麟光',en:'Linguang',line:'文湖線',lineEn:'Wenhu Line',lineColor:'#795548'},
  {id:'xinhai',zh:'辛亥',en:'Xinhai',line:'文湖線',lineEn:'Wenhu Line',lineColor:'#795548'},
  {id:'muzha',zh:'木柵',en:'Muzha',line:'文湖線',lineEn:'Wenhu Line',lineColor:'#795548'},
  {id:'dongwuyuan',zh:'動物園',en:'Taipei Zoo',line:'文湖線',lineEn:'Wenhu Line',lineColor:'#795548'},

  // 環狀線 Circular Line (黃線 Yellow)
  {id:'xinbuzhuang',zh:'新北產業園區',en:'New Taipei Industrial Park',line:'環狀線',lineEn:'Circular Line',lineColor:'#fdd835'},
  {id:'xinzhuang_c',zh:'新莊',en:'Xinzhuang',line:'環狀線',lineEn:'Circular Line',lineColor:'#fdd835'},
  {id:'touqian',zh:'頭前庄',en:'Touqianzhuang',line:'環狀線',lineEn:'Circular Line',lineColor:'#fdd835'},
  {id:'xinzhuang_jr_c',zh:'新莊國中',en:'Xinzhuang Junior High School',line:'環狀線',lineEn:'Circular Line',lineColor:'#fdd835'},
  {id:'danfeng_c',zh:'丹鳳',en:'Danfeng',line:'環狀線',lineEn:'Circular Line',lineColor:'#fdd835'},
  {id:'sanhe',zh:'三和國中',en:'Sanhe Junior High School',line:'環狀線',lineEn:'Circular Line',lineColor:'#fdd835'},
  {id:'sanchong_c',zh:'三重國小',en:'Sanchong Elementary School',line:'環狀線',lineEn:'Circular Line',lineColor:'#fdd835'},
  {id:'xiangan',zh:'先嗇宮',en:'Xian Se Gong',line:'環狀線',lineEn:'Circular Line',lineColor:'#fdd835'},
  {id:'cailiao',zh:'菜寮',en:'Cailiao',line:'環狀線',lineEn:'Circular Line',lineColor:'#fdd835'},
  {id:'jiangzicui_c',zh:'江子翠',en:'Jiangzicui',line:'環狀線',lineEn:'Circular Line',lineColor:'#fdd835'},
  {id:'zhonghe_gaozhong',zh:'中和高中',en:'Zhonghe Senior High School',line:'環狀線',lineEn:'Circular Line',lineColor:'#fdd835'},
  {id:'jingping_c',zh:'景平',en:'Jingping',line:'環狀線',lineEn:'Circular Line',lineColor:'#fdd835'},
  {id:'zhonghexinlu',zh:'中和',en:'Zhonghe',line:'環狀線',lineEn:'Circular Line',lineColor:'#fdd835'},
  {id:'qiaohe',zh:'橋和',en:'Qiaohe',line:'環狀線',lineEn:'Circular Line',lineColor:'#fdd835'},
  {id:'zhonghe_c',zh:'中正',en:'Zhongzheng',line:'環狀線',lineEn:'Circular Line',lineColor:'#fdd835'},
  {id:'xiulang',zh:'秀朗橋',en:'Xiulang Bridge',line:'環狀線',lineEn:'Circular Line',lineColor:'#fdd835'},

  // 桃園機場捷運 Taoyuan Airport MRT (紫線 Purple)
  {id:'taoyuan_hsr',zh:'高鐵桃園',en:'Taoyuan HSR',line:'桃園機場捷運',lineEn:'Taoyuan Airport MRT',lineColor:'#8e24aa'},
  {id:'taoyuan',zh:'桃園',en:'Taoyuan',line:'桃園機場捷運',lineEn:'Taoyuan Airport MRT',lineColor:'#8e24aa'},
  {id:'sanhe_a',zh:'三和',en:'Sanhe',line:'桃園機場捷運',lineEn:'Taoyuan Airport MRT',lineColor:'#8e24aa'},
  {id:'dayuan',zh:'大園',en:'Dayuan',line:'桃園機場捷運',lineEn:'Taoyuan Airport MRT',lineColor:'#8e24aa'},
  {id:'aerotropolis',zh:'航空城',en:'Aerotropolis',line:'桃園機場捷運',lineEn:'Taoyuan Airport MRT',lineColor:'#8e24aa'},
  {id:'t1',zh:'第一航廈',en:'Terminal 1',line:'桃園機場捷運',lineEn:'Taoyuan Airport MRT',lineColor:'#8e24aa'},
  {id:'t2',zh:'第二航廈',en:'Terminal 2',line:'桃園機場捷運',lineEn:'Taoyuan Airport MRT',lineColor:'#8e24aa'},
  {id:'linkou_a',zh:'林口',en:'Linkou',line:'桃園機場捷運',lineEn:'Taoyuan Airport MRT',lineColor:'#8e24aa'},
  {id:'changgung',zh:'長庚醫院',en:'Chang Gung Hospital',line:'桃園機場捷運',lineEn:'Taoyuan Airport MRT',lineColor:'#8e24aa'},
  {id:'xinzhuang_a',zh:'橋頭',en:'Qiaotou',line:'桃園機場捷運',lineEn:'Taoyuan Airport MRT',lineColor:'#8e24aa'},
  {id:'xinbei_industrial',zh:'新北產業園區',en:'New Taipei Industrial Park',line:'桃園機場捷運',lineEn:'Taoyuan Airport MRT',lineColor:'#8e24aa'},
  {id:'sanchong_a',zh:'三重',en:'Sanchong',line:'桃園機場捷運',lineEn:'Taoyuan Airport MRT',lineColor:'#8e24aa'},
  {id:'taipei_a',zh:'台北',en:'Taipei',line:'桃園機場捷運',lineEn:'Taoyuan Airport MRT',lineColor:'#8e24aa'},
];

window.AREAS = [
  {id:'wanhua_datong',en:'Wanhua & Datong',zh:'萬華・大同'},
  {id:'zhongzheng_ximen',en:'Zhongzheng & Ximen',zh:'中正・西門'},
  {id:'zhongshan_datong',en:'Zhongshan & Datong',zh:'中山・大同'},
  {id:'daan_zhongzheng',en:"Da'an & Zhongzheng",zh:'大安・中正'},
  {id:'xinyi_songshan',en:'Xinyi & Songshan',zh:'信義・松山'},
  {id:'shilin_beitou',en:'Shilin & Beitou',zh:'士林・北投'},
  {id:'neihu_nangang',en:'Neihu & Nangang',zh:'內湖・南港'},
  {id:'new_taipei',en:'New Taipei City',zh:'新北市'},
  {id:'taoyuan',en:'Taoyuan',zh:'桃園'},
  {id:'other',en:'Other Areas',zh:'其他地區'},
];

if(typeof module !== 'undefined') module.exports = {MRT_STATIONS: window.MRT_STATIONS, AREAS: window.AREAS};
