/**
 * MRT Station Data
 * Station names and route information sourced from public information provided by:
 * - Taipei Rapid Transit Corporation (TRTC) — www.metro.taipei
 * - Taoyuan Airport MRT Corporation (TYMC) — www.taoyuan-airport.com/airportmrt
 * Used for informational and navigation assistance purposes only.
 * All station names and route designations are trademarks of their respective operators.
 */
// ── MRT STATION DATABASE ──
// Format: { id, zh, en, line, lineEn, lineColor }
const MRT_STATIONS = [
  // 紅線 Tamsui-Xinyi Line
  {id:'xinbeitou',zh:'新北投',en:'Xinbeitou',line:'淡水信義線',lineEn:'Tamsui-Xinyi Line',lineColor:'#e53935'},
  {id:'beitou',zh:'北投',en:'Beitou',line:'淡水信義線',lineEn:'Tamsui-Xinyi Line',lineColor:'#e53935'},
  {id:'qiyan',zh:'奇岩',en:'Qiyan',line:'淡水信義線',lineEn:'Tamsui-Xinyi Line',lineColor:'#e53935'},
  {id:'hongshulin',zh:'紅樹林',en:'Hongshulin',line:'淡水信義線',lineEn:'Tamsui-Xinyi Line',lineColor:'#e53935'},
  {id:'zhuwei',zh:'竹圍',en:'Zhuwei',line:'淡水信義線',lineEn:'Tamsui-Xinyi Line',lineColor:'#e53935'},
  {id:'guandu',zh:'關渡',en:'Guandu',line:'淡水信義線',lineEn:'Tamsui-Xinyi Line',lineColor:'#e53935'},
  {id:'fuxinggang',zh:'復興崗',en:'Fuxinggang',line:'淡水信義線',lineEn:'Tamsui-Xinyi Line',lineColor:'#e53935'},
  {id:'zhongyi',zh:'忠義',en:'Zhongyi',line:'淡水信義線',lineEn:'Tamsui-Xinyi Line',lineColor:'#e53935'},
  {id:'xingtian',zh:'行天宮',en:'Xingtian Temple',line:'淡水信義線',lineEn:'Tamsui-Xinyi Line',lineColor:'#e53935'},
  {id:'zhongshan_jr',zh:'中山國中',en:'Zhongshan Junior High School',line:'淡水信義線',lineEn:'Tamsui-Xinyi Line',lineColor:'#e53935'},
  {id:'nanjingsanmin',zh:'南京三民',en:'Nanjing Sanmin',line:'淡水信義線',lineEn:'Tamsui-Xinyi Line',lineColor:'#e53935'},
  {id:'songshan_r',zh:'松山（紅）',en:'Songshan',line:'淡水信義線',lineEn:'Tamsui-Xinyi Line',lineColor:'#e53935'},
  {id:'tamsui',zh:'淡水',en:'Tamsui',line:'淡水信義線',lineEn:'Tamsui-Xinyi Line',lineColor:'#e53935'},
  {id:'hongshu',zh:'紅樹林',en:'Hongshulin',line:'淡水信義線',lineEn:'Tamsui-Xinyi Line',lineColor:'#e53935'},
  {id:'shipai',zh:'石牌',en:'Shipai',line:'淡水信義線',lineEn:'Tamsui-Xinyi Line',lineColor:'#e53935'},
  {id:'mingde',zh:'明德',en:'Mingde',line:'淡水信義線',lineEn:'Tamsui-Xinyi Line',lineColor:'#e53935'},
  {id:'zhishan',zh:'芝山',en:'Zhishan',line:'淡水信義線',lineEn:'Tamsui-Xinyi Line',lineColor:'#e53935'},
  {id:'tianmu',zh:'天母',en:'Tianmu',line:'淡水信義線',lineEn:'Tamsui-Xinyi Line',lineColor:'#e53935'},
  {id:'jiantan',zh:'劍潭',en:'Jiantan',line:'淡水信義線',lineEn:'Tamsui-Xinyi Line',lineColor:'#e53935'},
  {id:'shilin',zh:'士林',en:'Shilin',line:'淡水信義線',lineEn:'Tamsui-Xinyi Line',lineColor:'#e53935'},
  {id:'yuanshan',zh:'圓山',en:'Yuanshan',line:'淡水信義線',lineEn:'Tamsui-Xinyi Line',lineColor:'#e53935'},
  {id:'minquan_r',zh:'民權西路',en:'Minquan W. Rd.',line:'淡水信義線',lineEn:'Tamsui-Xinyi Line',lineColor:'#e53935'},
  {id:'shuanglian',zh:'雙連',en:'Shuanglian',line:'淡水信義線',lineEn:'Tamsui-Xinyi Line',lineColor:'#e53935'},
  {id:'zhongshan_r',zh:'中山',en:'Zhongshan',line:'淡水信義線',lineEn:'Tamsui-Xinyi Line',lineColor:'#e53935'},
  {id:'taida_hosp',zh:'台大醫院',en:'NTU Hospital',line:'淡水信義線',lineEn:'Tamsui-Xinyi Line',lineColor:'#e53935'},
  {id:'taipei_main',zh:'台北車站',en:'Taipei Main Station',line:'淡水信義線',lineEn:'Tamsui-Xinyi Line',lineColor:'#e53935'},
  {id:'chiang_kai_shek',zh:'中正紀念堂',en:'Chiang Kai-Shek Memorial Hall',line:'淡水信義線',lineEn:'Tamsui-Xinyi Line',lineColor:'#e53935'},
  {id:'dongmen',zh:'東門',en:'Dongmen',line:'淡水信義線',lineEn:'Tamsui-Xinyi Line',lineColor:'#e53935'},
  {id:'daan',zh:'大安',en:"Da'an",line:'淡水信義線',lineEn:'Tamsui-Xinyi Line',lineColor:'#e53935'},
  {id:'daan_park',zh:'大安森林公園',en:"Da'an Forest Park",line:'淡水信義線',lineEn:'Tamsui-Xinyi Line',lineColor:'#e53935'},
  {id:'xinyi_anhe',zh:'信義安和',en:'Xinyi Anhe',line:'淡水信義線',lineEn:'Tamsui-Xinyi Line',lineColor:'#e53935'},
  {id:'taipei101',zh:'台北101/世貿',en:'Taipei 101/World Trade Center',line:'淡水信義線',lineEn:'Tamsui-Xinyi Line',lineColor:'#e53935'},
  {id:'xiangshan',zh:'象山',en:'Xiangshan',line:'淡水信義線',lineEn:'Tamsui-Xinyi Line',lineColor:'#e53935'},

  // 綠線 Songshan-Xindian Line
  {id:'songshan_g',zh:'松山',en:'Songshan',line:'松山新店線',lineEn:'Songshan-Xindian Line',lineColor:'#43a047'},
  {id:'nanjing_fuxing',zh:'南京復興',en:'Nanjing Fuxing',line:'松山新店線',lineEn:'Songshan-Xindian Line',lineColor:'#43a047'},
  {id:'zhongxiao_fuxing',zh:'忠孝復興',en:'Zhongxiao Fuxing',line:'松山新店線',lineEn:'Songshan-Xindian Line',lineColor:'#43a047'},
  {id:'zhongxiao_xinsheng',zh:'忠孝新生',en:'Zhongxiao Xinsheng',line:'松山新店線',lineEn:'Songshan-Xindian Line',lineColor:'#43a047'},
  {id:'guting_g',zh:'古亭',en:'Guting',line:'松山新店線',lineEn:'Songshan-Xindian Line',lineColor:'#43a047'},
  {id:'taipower',zh:'台電大樓',en:'Taipower Building',line:'松山新店線',lineEn:'Songshan-Xindian Line',lineColor:'#43a047'},
  {id:'gongguan',zh:'公館',en:'Gongguan',line:'松山新店線',lineEn:'Songshan-Xindian Line',lineColor:'#43a047'},
  {id:'wanlong',zh:'萬隆',en:'Wanlong',line:'松山新店線',lineEn:'Songshan-Xindian Line',lineColor:'#43a047'},
  {id:'jingmei',zh:'景美',en:'Jingmei',line:'松山新店線',lineEn:'Songshan-Xindian Line',lineColor:'#43a047'},
  {id:'dapinglin',zh:'大坪林',en:'Dapinglin',line:'松山新店線',lineEn:'Songshan-Xindian Line',lineColor:'#43a047'},
  {id:'qizhang',zh:'七張',en:'Qizhang',line:'松山新店線',lineEn:'Songshan-Xindian Line',lineColor:'#43a047'},
  {id:'xindian_city_hall',zh:'新店市政府',en:'Xindian City Hall',line:'松山新店線',lineEn:'Songshan-Xindian Line',lineColor:'#43a047'},
  {id:'xindian',zh:'新店',en:'Xindian',line:'松山新店線',lineEn:'Songshan-Xindian Line',lineColor:'#43a047'},
  {id:'xindian',zh:'新店',en:'Xindian',line:'松山新店線',lineEn:'Songshan-Xindian Line',lineColor:'#43a047'},
  {id:'xiaobitan',zh:'小碧潭',en:'Xiaobitan',line:'松山新店線',lineEn:'Songshan-Xindian Line',lineColor:'#43a047'},
  {id:'beimen_g',zh:'北門',en:'Beimen',line:'松山新店線',lineEn:'Songshan-Xindian Line',lineColor:'#43a047'},
  {id:'ximen_g',zh:'西門',en:'Ximen',line:'松山新店線',lineEn:'Songshan-Xindian Line',lineColor:'#43a047'},
  {id:'zhonghua_rd',zh:'中和',en:'Zhonghe',line:'松山新店線',lineEn:'Songshan-Xindian Line',lineColor:'#43a047'},

  // 橘線 Zhonghe-Xinlu Line
  {id:'nanshijiao',zh:'南勢角',en:'Nanshijiao',line:'中和新蘆線',lineEn:'Zhonghe-Xinlu Line',lineColor:'#fb8c00'},
  {id:'jingping',zh:'景平',en:'Jingping',line:'中和新蘆線',lineEn:'Zhonghe-Xinlu Line',lineColor:'#fb8c00'},
  {id:'jingan',zh:'景安',en:"Jing'an",line:'中和新蘆線',lineEn:'Zhonghe-Xinlu Line',lineColor:'#fb8c00'},
  {id:'yongan_market',zh:'永安市場',en:"Yong'an Market",line:'中和新蘆線',lineEn:'Zhonghe-Xinlu Line',lineColor:'#fb8c00'},
  {id:'dingxi',zh:'頂溪',en:'Dingxi',line:'中和新蘆線',lineEn:'Zhonghe-Xinlu Line',lineColor:'#fb8c00'},
  {id:'guting_o',zh:'古亭',en:'Guting',line:'中和新蘆線',lineEn:'Zhonghe-Xinlu Line',lineColor:'#fb8c00'},
  {id:'dongmen_o',zh:'東門',en:'Dongmen',line:'中和新蘆線',lineEn:'Zhonghe-Xinlu Line',lineColor:'#fb8c00'},
  {id:'zhongxiao_xinsheng_o',zh:'忠孝新生',en:'Zhongxiao Xinsheng',line:'中和新蘆線',lineEn:'Zhonghe-Xinlu Line',lineColor:'#fb8c00'},
  {id:'songjiang_nanjing',zh:'松江南京',en:'Songjiang Nanjing',line:'中和新蘆線',lineEn:'Zhonghe-Xinlu Line',lineColor:'#fb8c00'},
  {id:'xingtian_o',zh:'行天宮',en:'Xingtian Temple',line:'中和新蘆線',lineEn:'Zhonghe-Xinlu Line',lineColor:'#fb8c00'},
  {id:'zhongshan_o',zh:'中山',en:'Zhongshan',line:'中和新蘆線',lineEn:'Zhonghe-Xinlu Line',lineColor:'#fb8c00'},
  {id:'minquan_o',zh:'民權西路',en:'Minquan W. Rd.',line:'中和新蘆線',lineEn:'Zhonghe-Xinlu Line',lineColor:'#fb8c00'},
  {id:'daqiaotou',zh:'大橋頭',en:'Daqiaotou',line:'中和新蘆線',lineEn:'Zhonghe-Xinlu Line',lineColor:'#fb8c00'},
  {id:'xinpu',zh:'新埔',en:'Xinpu',line:'中和新蘆線',lineEn:'Zhonghe-Xinlu Line',lineColor:'#fb8c00'},
  {id:'jiangzicui',zh:'江子翠',en:'Jiangzicui',line:'中和新蘆線',lineEn:'Zhonghe-Xinlu Line',lineColor:'#fb8c00'},
  {id:'xinzhuang',zh:'新莊',en:'Xinzhuang',line:'中和新蘆線',lineEn:'Zhonghe-Xinlu Line',lineColor:'#fb8c00'},
  {id:'taishan',zh:'泰山',en:'Taishan',line:'中和新蘆線',lineEn:'Zhonghe-Xinlu Line',lineColor:'#fb8c00'},
  {id:'fuxinggang_o',zh:'輔大',en:'Fu Jen University',line:'中和新蘆線',lineEn:'Zhonghe-Xinlu Line',lineColor:'#fb8c00'},
  {id:'danfeng',zh:'丹鳳',en:'Danfeng',line:'中和新蘆線',lineEn:'Zhonghe-Xinlu Line',lineColor:'#fb8c00'},
  {id:'luzhou',zh:'蘆洲',en:'Luzhou',line:'中和新蘆線',lineEn:'Zhonghe-Xinlu Line',lineColor:'#fb8c00'},

  // 藍線 Bannan Line
  {id:'yingge',zh:'鶯歌',en:'Yingge',line:'板南線',lineEn:'Bannan Line',lineColor:'#1e88e5'},
  {id:'sanxia',zh:'三峽',en:'Sanxia',line:'板南線',lineEn:'Bannan Line',lineColor:'#1e88e5'},
  {id:'anping',zh:'安平',en:'Anping',line:'板南線',lineEn:'Bannan Line',lineColor:'#1e88e5'},
  {id:'dingpu',zh:'頂埔',en:'Dingpu',line:'板南線',lineEn:'Bannan Line',lineColor:'#1e88e5'},
  {id:'tudigong',zh:'土城',en:'Tucheng',line:'板南線',lineEn:'Bannan Line',lineColor:'#1e88e5'},
  {id:'haishan',zh:'海山',en:'Haishan',line:'板南線',lineEn:'Bannan Line',lineColor:'#1e88e5'},
  {id:'yongning',zh:'永寧',en:'Yongning',line:'板南線',lineEn:'Bannan Line',lineColor:'#1e88e5'},
  {id:'sanchong',zh:'三重',en:'Sanchong',line:'板南線',lineEn:'Bannan Line',lineColor:'#1e88e5'},
  {id:'fuzhong',zh:'府中',en:'Fuzhong',line:'板南線',lineEn:'Bannan Line',lineColor:'#1e88e5'},
  {id:'banqiao',zh:'板橋',en:'Banqiao',line:'板南線',lineEn:'Bannan Line',lineColor:'#1e88e5'},
  {id:'xinfuqian',zh:'新埔',en:'Xinpu',line:'板南線',lineEn:'Bannan Line',lineColor:'#1e88e5'},
  {id:'jiangzicui_b',zh:'江子翠',en:'Jiangzicui',line:'板南線',lineEn:'Bannan Line',lineColor:'#1e88e5'},
  {id:'longshan_temple',zh:'龍山寺',en:'Longshan Temple',line:'板南線',lineEn:'Bannan Line',lineColor:'#1e88e5'},
  {id:'ximen_b',zh:'西門',en:'Ximen',line:'板南線',lineEn:'Bannan Line',lineColor:'#1e88e5'},
  {id:'beimen_b',zh:'北門',en:'Beimen',line:'板南線',lineEn:'Bannan Line',lineColor:'#1e88e5'},
  {id:'taipei_main_b',zh:'台北車站',en:'Taipei Main Station',line:'板南線',lineEn:'Bannan Line',lineColor:'#1e88e5'},
  {id:'shandao_temple',zh:'善導寺',en:'Shandao Temple',line:'板南線',lineEn:'Bannan Line',lineColor:'#1e88e5'},
  {id:'zhongxiao_xinsheng_b',zh:'忠孝新生',en:'Zhongxiao Xinsheng',line:'板南線',lineEn:'Bannan Line',lineColor:'#1e88e5'},
  {id:'zhongxiao_fuxing_b',zh:'忠孝復興',en:'Zhongxiao Fuxing',line:'板南線',lineEn:'Bannan Line',lineColor:'#1e88e5'},
  {id:'zhongxiao_dunhua',zh:'忠孝敦化',en:'Zhongxiao Dunhua',line:'板南線',lineEn:'Bannan Line',lineColor:'#1e88e5'},
  {id:'guofu',zh:'國父紀念館',en:'Sun Yat-Sen Memorial Hall',line:'板南線',lineEn:'Bannan Line',lineColor:'#1e88e5'},
  {id:'market',zh:'市政府',en:'City Hall',line:'板南線',lineEn:'Bannan Line',lineColor:'#1e88e5'},
  {id:'yongchun',zh:'永春',en:'Yongchun',line:'板南線',lineEn:'Bannan Line',lineColor:'#1e88e5'},
  {id:'houshanpi',zh:'後山埤',en:'Houshanpi',line:'板南線',lineEn:'Bannan Line',lineColor:'#1e88e5'},
  {id:'kunyang',zh:'昆陽',en:'Kunyang',line:'板南線',lineEn:'Bannan Line',lineColor:'#1e88e5'},
  {id:'nangang',zh:'南港',en:'Nangang',line:'板南線',lineEn:'Bannan Line',lineColor:'#1e88e5'},
  {id:'nangang_exhibition',zh:'南港展覽館',en:'Nangang Exhibition Center',line:'板南線',lineEn:'Bannan Line',lineColor:'#1e88e5'},

  // 黃線 Circular Line
  {id:'xinlu',zh:'新蘆',en:'Xinlu',line:'環狀線',lineEn:'Circular Line',lineColor:'#fdd835'},
  {id:'sanhe',zh:'三和國中',en:'Sanhe Junior High School',line:'環狀線',lineEn:'Circular Line',lineColor:'#fdd835'},
  {id:'cailiao',zh:'菜寮',en:'Cailiao',line:'環狀線',lineEn:'Circular Line',lineColor:'#fdd835'},
  {id:'xinzhuang_c',zh:'新莊',en:'Xinzhuang',line:'環狀線',lineEn:'Circular Line',lineColor:'#fdd835'},
  {id:'touqian',zh:'頭前庄',en:'Touqianzhuang',line:'環狀線',lineEn:'Circular Line',lineColor:'#fdd835'},
  {id:'xintaiwu',zh:'新泰武',en:'Xintaiwu',line:'環狀線',lineEn:'Circular Line',lineColor:'#fdd835'},
  {id:'jinganzhuang',zh:'幸安庄',en:"Jing'anzhuang",line:'環狀線',lineEn:'Circular Line',lineColor:'#fdd835'},
  {id:'linkou',zh:'林口',en:'Linkou',line:'環狀線',lineEn:'Circular Line',lineColor:'#fdd835'},
  {id:'xinzhuang_jr',zh:'新莊國中',en:'Xinzhuang Junior High School',line:'環狀線',lineEn:'Circular Line',lineColor:'#fdd835'},
  {id:'dangdutou',zh:'丹鳳',en:'Danfeng',line:'環狀線',lineEn:'Circular Line',lineColor:'#fdd835'},
  {id:'xindian_c',zh:'新店',en:'Xindian',line:'環狀線',lineEn:'Circular Line',lineColor:'#fdd835'},
  {id:'dahua',zh:'大華',en:'Dahua',line:'環狀線',lineEn:'Circular Line',lineColor:'#fdd835'},
  {id:'shulin',zh:'樹林',en:'Shulin',line:'環狀線',lineEn:'Circular Line',lineColor:'#fdd835'},
  {id:'zhonghe_c',zh:'中和',en:'Zhonghe',line:'環狀線',lineEn:'Circular Line',lineColor:'#fdd835'},
  {id:'qiaohe',zh:'橋和',en:'Qiaohe',line:'環狀線',lineEn:'Circular Line',lineColor:'#fdd835'},
  {id:'zhonghe_gaozhong',zh:'中和高中',en:'Zhonghe Senior High School',line:'環狀線',lineEn:'Circular Line',lineColor:'#fdd835'},
  {id:'jingping_c',zh:'景平',en:'Jingping',line:'環狀線',lineEn:'Circular Line',lineColor:'#fdd835'},
  {id:'xidingpu',zh:'頂溪',en:'Dingxi',line:'環狀線',lineEn:'Circular Line',lineColor:'#fdd835'},
  {id:'xiulang',zh:'秀朗橋',en:'Xiulang Bridge',line:'環狀線',lineEn:'Circular Line',lineColor:'#fdd835'},
  {id:'yonghe',zh:'永和',en:'Yonghe',line:'環狀線',lineEn:'Circular Line',lineColor:'#fdd835'},
  {id:'dingxi_c',zh:'頂溪',en:'Dingxi',line:'環狀線',lineEn:'Circular Line',lineColor:'#fdd835'},
  {id:'shuanghe',zh:'雙和',en:'Shuanghe',line:'環狀線',lineEn:'Circular Line',lineColor:'#fdd835'},
  {id:'zhonghe_shenzhi',zh:'中和',en:'Zhonghe',line:'環狀線',lineEn:'Circular Line',lineColor:'#fdd835'},

  // 桃園機場捷運 Taoyuan Airport MRT
  {id:'taoyuan_hsr',zh:'高鐵桃園',en:'Taoyuan HSR',line:'桃園機場捷運',lineEn:'Taoyuan Airport MRT',lineColor:'#8e24aa'},
  {id:'taoyuan_main',zh:'桃園',en:'Taoyuan',line:'桃園機場捷運',lineEn:'Taoyuan Airport MRT',lineColor:'#8e24aa'},
  {id:'sanhe_a',zh:'三和',en:'Sanhe',line:'桃園機場捷運',lineEn:'Taoyuan Airport MRT',lineColor:'#8e24aa'},
  {id:'daxi',zh:'大溪',en:'Daxi',line:'桃園機場捷運',lineEn:'Taoyuan Airport MRT',lineColor:'#8e24aa'},
  {id:'aerotropolis',zh:'航空城',en:'Aerotropolis',line:'桃園機場捷運',lineEn:'Taoyuan Airport MRT',lineColor:'#8e24aa'},
  {id:'t1',zh:'第一航廈',en:'Terminal 1',line:'桃園機場捷運',lineEn:'Taoyuan Airport MRT',lineColor:'#8e24aa'},
  {id:'t2',zh:'第二航廈',en:'Terminal 2',line:'桃園機場捷運',lineEn:'Taoyuan Airport MRT',lineColor:'#8e24aa'},
  {id:'dayuan',zh:'大園',en:'Dayuan',line:'桃園機場捷運',lineEn:'Taoyuan Airport MRT',lineColor:'#8e24aa'},
  {id:'huanai',zh:'華泥',en:'Huanai',line:'桃園機場捷運',lineEn:'Taoyuan Airport MRT',lineColor:'#8e24aa'},
  {id:'zhongli',zh:'中壢',en:'Zhongli',line:'桃園機場捷運',lineEn:'Taoyuan Airport MRT',lineColor:'#8e24aa'},
  {id:'lindian',zh:'領航',en:'Linkou',line:'桃園機場捷運',lineEn:'Taoyuan Airport MRT',lineColor:'#8e24aa'},
  {id:'changgung',zh:'長庚醫院',en:'Chang Gung Hospital',line:'桃園機場捷運',lineEn:'Taoyuan Airport MRT',lineColor:'#8e24aa'},
  {id:'taoyuan_airport_a6',zh:'泰山貴和',en:'Taishan Guihe',line:'桃園機場捷運',lineEn:'Taoyuan Airport MRT',lineColor:'#8e24aa'},
  {id:'xinzhuang_a7',zh:'新莊副都心',en:'Xinzhuang Sub-City Center',line:'桃園機場捷運',lineEn:'Taoyuan Airport MRT',lineColor:'#8e24aa'},
  {id:'sanchong_a8',zh:'三重',en:'Sanchong',line:'桃園機場捷運',lineEn:'Taoyuan Airport MRT',lineColor:'#8e24aa'},
  {id:'taipei_main_a12',zh:'台北',en:'Taipei',line:'桃園機場捷運',lineEn:'Taoyuan Airport MRT',lineColor:'#8e24aa'},
  {id:'sanzhong_a9',zh:'三重國小',en:'Sanchong Elementary School',line:'桃園機場捷運',lineEn:'Taoyuan Airport MRT',lineColor:'#8e24aa'},
  {id:'xinbei_a10',zh:'新北產業園區',en:'New Taipei Industrial Park',line:'桃園機場捷運',lineEn:'Taoyuan Airport MRT',lineColor:'#8e24aa'},
  {id:'xinzhuang_a11',zh:'橋頭',en:'Qiaotou',line:'桃園機場捷運',lineEn:'Taoyuan Airport MRT',lineColor:'#8e24aa'},
  {id:'neihu',zh:'內湖',en:'Neihu',line:'文湖線',lineEn:'Wenhu Line',lineColor:'#795548'},
];

// ── AREA DATABASE ──
const AREAS = [
  {id:'wanhua_datong', en:'Wanhua & Datong', zh:'萬華・大同', desc:'Longshan Temple, Dihua St, Dadaocheng'},
  {id:'zhongzheng_ximen', en:'Zhongzheng & Ximen', zh:'中正・西門', desc:'CKS Memorial, Ximen, Ximending'},
  {id:'zhongshan_datong', en:'Zhongshan & Datong', zh:'中山・大同', desc:'Zhongshan, Dihua St, Design District'},
  {id:'daan_zhongzheng', en:"Da'an & Zhongzheng", zh:'大安・中正', desc:"Yongkang St, Shida Night Market, Da'an Park"},
  {id:'xinyi_songshan', en:'Xinyi & Songshan', zh:'信義・松山', desc:'Taipei 101, Raohe Night Market, Elephant Mountain'},
  {id:'shilin_beitou', en:'Shilin & Beitou', zh:'士林・北投', desc:'Shilin Night Market, National Palace Museum, Beitou Hot Springs'},
  {id:'neihu_nangang', en:'Neihu & Nangang', zh:'內湖・南港', desc:'Nangang Exhibition, Tech Hub'},
  {id:'new_taipei', en:'New Taipei City', zh:'新北市', desc:'Jiufen, Tamsui, Danshui, Sanxia'},
  {id:'taoyuan', en:'Taoyuan', zh:'桃園', desc:'Taoyuan Airport, Dayuan'},
  {id:'other', en:'Other Areas', zh:'其他地區', desc:'Outside Taipei Metro Area'},
];

if(typeof module !== 'undefined') module.exports = {MRT_STATIONS, AREAS};
